export const playgroundBlocks = [
  { title: "Records Table · theshanelevine", category: "Tablas", href: "/playground/21st-dev/records-table-theshanelevine", provider: "21st.dev", kind: "features", description: "Tabla compacta con selección, columnas ordenables y resumen de registros." },
  {
    "title": "Line Charts 4 · sean0205",
    "category": "Gráficas",
    "href": "/playground/21st-dev/line-charts-4-sean0205",
    "provider": "21st.dev",
    "kind": "features",
    "description": "Line Charts 4: ejemplo interactivo de gráficas con datos de muestra."
  },
  {
    "title": "Chart · shadcn",
    "category": "Gráficas",
    "href": "/playground/21st-dev/chart-shadcn",
    "provider": "21st.dev",
    "kind": "features",
    "description": "Chart: ejemplo interactivo de gráficas con datos de muestra."
  },
  {
    "title": "Line Charts 8 · sean0205",
    "category": "Gráficas",
    "href": "/playground/21st-dev/line-charts-8-sean0205",
    "provider": "21st.dev",
    "kind": "features",
    "description": "Line Charts 8: ejemplo interactivo de gráficas con datos de muestra."
  },
  {
    "title": "Radar Chart · intentui",
    "category": "Gráficas",
    "href": "/playground/21st-dev/radar-chart-intentui",
    "provider": "21st.dev",
    "kind": "features",
    "description": "Radar Chart: ejemplo interactivo de gráficas con datos de muestra."
  },
  {
    "title": "Area Charts 1 · sean0205",
    "category": "Gráficas",
    "href": "/playground/21st-dev/area-charts-1-sean0205",
    "provider": "21st.dev",
    "kind": "features",
    "description": "Area Charts 1: ejemplo interactivo de gráficas con datos de muestra."
  },
  {
    "title": "Line Charts 9 · sean0205",
    "category": "Gráficas",
    "href": "/playground/21st-dev/line-charts-9-sean0205",
    "provider": "21st.dev",
    "kind": "features",
    "description": "Line Charts 9: ejemplo interactivo de gráficas con datos de muestra."
  },
  {
    "title": "Candle Chart · ssychui",
    "category": "Gráficas",
    "href": "/playground/21st-dev/candle-chart-ssychui",
    "provider": "21st.dev",
    "kind": "features",
    "description": "Candle Chart: ejemplo interactivo de gráficas con datos de muestra."
  },
  {
    "title": "Line Chart · LegionWebDev",
    "category": "Gráficas",
    "href": "/playground/21st-dev/line-chart-legionwebdev",
    "provider": "21st.dev",
    "kind": "features",
    "description": "Line Chart: ejemplo interactivo de gráficas con datos de muestra."
  },
  {
    "title": "Funnel Chart · bklitai",
    "category": "Gráficas",
    "href": "/playground/21st-dev/funnel-chart-bklitai",
    "provider": "21st.dev",
    "kind": "features",
    "description": "Funnel Chart: ejemplo interactivo de gráficas con datos de muestra."
  },
  {
    "title": "Line Charts 5 · sean0205",
    "category": "Gráficas",
    "href": "/playground/21st-dev/line-charts-5-sean0205",
    "provider": "21st.dev",
    "kind": "features",
    "description": "Line Charts 5: ejemplo interactivo de gráficas con datos de muestra."
  },
  {
    "title": "Chart Tooltip · uiable",
    "category": "Gráficas",
    "href": "/playground/21st-dev/chart-tooltip-uiable",
    "provider": "21st.dev",
    "kind": "features",
    "description": "Chart Tooltip: ejemplo interactivo de gráficas con datos de muestra."
  },
  {
    "title": "Pie chart · airbnb",
    "category": "Gráficas",
    "href": "/playground/21st-dev/pie-chart-airbnb",
    "provider": "21st.dev",
    "kind": "features",
    "description": "Pie chart: ejemplo interactivo de gráficas con datos de muestra."
  },
  {
    "title": "GitHub Contribution Graph 3D Heatmap · kedhareswer",
    "category": "Gráficas",
    "href": "/playground/21st-dev/contribution-skyline-kedhareswer",
    "provider": "21st.dev",
    "kind": "features",
    "description": "GitHub Contribution Graph 3D Heatmap: ejemplo interactivo de gráficas con datos de muestra."
  },
  {
    "title": "Funnel Chart Big · reaviz",
    "category": "Gráficas",
    "href": "/playground/21st-dev/funnel-chart-big-reaviz",
    "provider": "21st.dev",
    "kind": "features",
    "description": "Funnel Chart Big: ejemplo interactivo de gráficas con datos de muestra."
  },
  {
    "title": "Bar Chart · LegionWebDev",
    "category": "Gráficas",
    "href": "/playground/21st-dev/bar-chart-legionwebdev",
    "provider": "21st.dev",
    "kind": "features",
    "description": "Bar Chart: ejemplo interactivo de gráficas con datos de muestra."
  },
  {
    "title": "Area Chart · SubframeApp",
    "category": "Gráficas",
    "href": "/playground/21st-dev/area-chart-subframeapp",
    "provider": "21st.dev",
    "kind": "features",
    "description": "Area Chart: ejemplo interactivo de gráficas con datos de muestra."
  },
  {
    "title": "Glare Cards · daiwiikharihar",
    "category": "Tarjetas",
    "href": "/playground/21st-dev/glare-cards-daiwiikharihar",
    "provider": "21st.dev",
    "kind": "features",
    "description": "Glare Cards: ejemplo interactivo de tarjetas con datos de muestra."
  },
  {
    "title": "Area Chart · bklitai",
    "category": "Gráficas",
    "href": "/playground/21st-dev/area-chart-bklitai",
    "provider": "21st.dev",
    "kind": "features",
    "description": "Area Chart: ejemplo interactivo de gráficas con datos de muestra."
  },
  {
    "title": "Line Charts 1 · sean0205",
    "category": "Gráficas",
    "href": "/playground/21st-dev/line-charts-1-sean0205",
    "provider": "21st.dev",
    "kind": "features",
    "description": "Line Charts 1: ejemplo interactivo de gráficas con datos de muestra."
  },
  {
    "title": "Line Graph Statistics · ravikatiyar162",
    "category": "Estadísticas",
    "href": "/playground/21st-dev/line-graph-statistics-ravikatiyar162",
    "provider": "21st.dev",
    "kind": "features",
    "description": "Line Graph Statistics: ejemplo interactivo de estadísticas con datos de muestra."
  },
  {
    "title": "Animated Card Diagram · badtzx0",
    "category": "Tarjetas",
    "href": "/playground/21st-dev/animated-card-diagram-badtzx0",
    "provider": "21st.dev",
    "kind": "features",
    "description": "Animated Card Diagram: ejemplo interactivo de tarjetas con datos de muestra."
  },
  {
    "title": "Progress Metric Card · makviesainte",
    "category": "Estadísticas",
    "href": "/playground/21st-dev/progress-metric-card-makviesainte",
    "provider": "21st.dev",
    "kind": "features",
    "description": "Progress Metric Card: ejemplo interactivo de estadísticas con datos de muestra."
  },
  {
    "title": "Bar Chart · intentui",
    "category": "Gráficas",
    "href": "/playground/21st-dev/bar-chart-intentui",
    "provider": "21st.dev",
    "kind": "features",
    "description": "Bar Chart: ejemplo interactivo de gráficas con datos de muestra."
  },
  {
    "title": "Area Chart · reaviz",
    "category": "Gráficas",
    "href": "/playground/21st-dev/area-chart-1-reaviz",
    "provider": "21st.dev",
    "kind": "features",
    "description": "Area Chart: ejemplo interactivo de gráficas con datos de muestra."
  },
  {
    "title": "Line Charts 6 · sean0205",
    "category": "Gráficas",
    "href": "/playground/21st-dev/line-charts-6-sean0205",
    "provider": "21st.dev",
    "kind": "features",
    "description": "Line Charts 6: ejemplo interactivo de gráficas con datos de muestra."
  },
  {
    "title": "Pie Chart · LegionWebDev",
    "category": "Gráficas",
    "href": "/playground/21st-dev/pie-chart-legionwebdev",
    "provider": "21st.dev",
    "kind": "features",
    "description": "Pie Chart: ejemplo interactivo de gráficas con datos de muestra."
  },
  {
    "title": "Radar Chart · LegionWebDev",
    "category": "Gráficas",
    "href": "/playground/21st-dev/radar-chart-legionwebdev",
    "provider": "21st.dev",
    "kind": "features",
    "description": "Radar Chart: ejemplo interactivo de gráficas con datos de muestra."
  },
  {
    "title": "Area Charts 2 · sean0205",
    "category": "Gráficas",
    "href": "/playground/21st-dev/area-charts-2-sean0205",
    "provider": "21st.dev",
    "kind": "features",
    "description": "Area Charts 2: ejemplo interactivo de gráficas con datos de muestra."
  },
  {
    "title": "Charts · lyanchouss",
    "category": "Gráficas",
    "href": "/playground/21st-dev/charts-lyanchouss",
    "provider": "21st.dev",
    "kind": "features",
    "description": "Charts: ejemplo interactivo de gráficas con datos de muestra."
  },
  {
    "title": "Interactive Logs Table · moumensoliman",
    "category": "Tablas",
    "href": "/playground/21st-dev/interactive-logs-table-shadcnui-moumensoliman",
    "provider": "21st.dev",
    "kind": "features",
    "description": "Interactive Logs Table: ejemplo interactivo de tablas con datos de muestra."
  },
  {
    "title": "Donut Chart · ravikatiyar162",
    "category": "Gráficas",
    "href": "/playground/21st-dev/donut-chart-ravikatiyar162",
    "provider": "21st.dev",
    "kind": "features",
    "description": "Donut Chart: ejemplo interactivo de gráficas con datos de muestra."
  },
  {
    "title": "Area Chart · LegionWebDev",
    "category": "Gráficas",
    "href": "/playground/21st-dev/area-chart-legionwebdev",
    "provider": "21st.dev",
    "kind": "features",
    "description": "Area Chart: ejemplo interactivo de gráficas con datos de muestra."
  },
  {
    "title": "Dashboard Chart 6",
    "category": "Gráficas",
    "href": "/playground/paceui/dashboard-chart-6",
    "provider": "Pace UI",
    "kind": "features",
    "description": "Dashboard Chart 6: ejemplo interactivo de gráficas con datos de muestra."
  },
  {
    "title": "Dashboard Chart 5",
    "category": "Gráficas",
    "href": "/playground/paceui/dashboard-chart-5",
    "provider": "Pace UI",
    "kind": "features",
    "description": "Dashboard Chart 5: ejemplo interactivo de gráficas con datos de muestra."
  },
  {
    "title": "Dashboard Chart 4",
    "category": "Gráficas",
    "href": "/playground/paceui/dashboard-chart-4",
    "provider": "Pace UI",
    "kind": "features",
    "description": "Dashboard Chart 4: ejemplo interactivo de gráficas con datos de muestra."
  },
  {
    "title": "Dashboard Chart 3",
    "category": "Gráficas",
    "href": "/playground/paceui/dashboard-chart-3",
    "provider": "Pace UI",
    "kind": "features",
    "description": "Dashboard Chart 3: ejemplo interactivo de gráficas con datos de muestra."
  },
  {
    "title": "Dashboard Chart 2",
    "category": "Gráficas",
    "href": "/playground/paceui/dashboard-chart-2",
    "provider": "Pace UI",
    "kind": "features",
    "description": "Dashboard Chart 2: ejemplo interactivo de gráficas con datos de muestra."
  },
  {
    "title": "Dashboard Chart 1",
    "category": "Gráficas",
    "href": "/playground/paceui/dashboard-chart-1",
    "provider": "Pace UI",
    "kind": "features",
    "description": "Dashboard Chart 1: ejemplo interactivo de gráficas con datos de muestra."
  },
  {
    "title": "App Analytics 3",
    "category": "Dashboards",
    "href": "/playground/paceui/app-analytics-3",
    "provider": "Pace UI",
    "kind": "features",
    "description": "App Analytics 3: ejemplo interactivo de dashboards con datos de muestra."
  },
  {
    "title": "App Analytics 2",
    "category": "Dashboards",
    "href": "/playground/paceui/app-analytics-2",
    "provider": "Pace UI",
    "kind": "features",
    "description": "App Analytics 2: ejemplo interactivo de dashboards con datos de muestra."
  },
  {
    "title": "App Analytics 1",
    "category": "Dashboards",
    "href": "/playground/paceui/app-analytics-1",
    "provider": "Pace UI",
    "kind": "features",
    "description": "App Analytics 1: ejemplo interactivo de dashboards con datos de muestra."
  },
  {
    "title": "App Education 1",
    "category": "Dashboards",
    "href": "/playground/paceui/app-education-1",
    "provider": "Pace UI",
    "kind": "features",
    "description": "App Education 1: ejemplo interactivo de dashboards con datos de muestra."
  },
  {
    "title": "App Finance 1",
    "category": "Dashboards",
    "href": "/playground/paceui/app-finance-1",
    "provider": "Pace UI",
    "kind": "features",
    "description": "App Finance 1: ejemplo interactivo de dashboards con datos de muestra."
  },
  {
    "title": "App Health 1",
    "category": "Dashboards",
    "href": "/playground/paceui/app-health-1",
    "provider": "Pace UI",
    "kind": "features",
    "description": "App Health 1: ejemplo interactivo de dashboards con datos de muestra."
  },
  {
    "title": "Dashboard Stat 4",
    "category": "Estadísticas",
    "href": "/playground/paceui/dashboard-stat-4",
    "provider": "Pace UI",
    "kind": "features",
    "description": "Dashboard Stat 4: ejemplo interactivo de estadísticas con datos de muestra."
  },
  {
    "title": "Dashboard Stat 3",
    "category": "Estadísticas",
    "href": "/playground/paceui/dashboard-stat-3",
    "provider": "Pace UI",
    "kind": "features",
    "description": "Dashboard Stat 3: ejemplo interactivo de estadísticas con datos de muestra."
  },
  {
    "title": "Dashboard Stat 2",
    "category": "Estadísticas",
    "href": "/playground/paceui/dashboard-stat-2",
    "provider": "Pace UI",
    "kind": "features",
    "description": "Dashboard Stat 2: ejemplo interactivo de estadísticas con datos de muestra."
  },
  {
    "title": "Dashboard Stat 1",
    "category": "Estadísticas",
    "href": "/playground/paceui/dashboard-stat-1",
    "provider": "Pace UI",
    "kind": "features",
    "description": "Dashboard Stat 1: ejemplo interactivo de estadísticas con datos de muestra."
  },
  {
    "title": "Dashboard Table 3",
    "category": "Tablas",
    "href": "/playground/paceui/dashboard-table-3",
    "provider": "Pace UI",
    "kind": "features",
    "description": "Dashboard Table 3: ejemplo interactivo de tablas con datos de muestra."
  },
  {
    title: "Boleto clásico",
    category: "Boletos",
    href: "/playground/boletera/receipt-ticket",
    provider: "Boletera",
    kind: "event",
    description: "Boleto estilo recibo en vertical y horizontal, con QR y talón desprendible.",
  },
  {
    title: "Sign Up Split Panel",
    category: "Autenticación",
    href: "/playground/21st-dev/sign-up-1",
    provider: "21st.dev",
    kind: "features",
    description: "Registro en dos columnas con acceso social y panel de testimonio.",
  },
  {
    title: "Sign In Card",
    category: "Autenticación",
    href: "/playground/21st-dev/sign-in-card-2",
    provider: "21st.dev",
    kind: "features",
    description: "Tarjeta de acceso con luces animadas, fondo morado e inclinación interactiva.",
  },
  {
    title: "Modern & Stunning Sign In",
    category: "Autenticación",
    href: "/playground/21st-dev/modern-stunning-sign-in",
    provider: "21st.dev",
    kind: "features",
    description: "Formulario de acceso oscuro con tarjeta translúcida y avatares.",
  },
  {
    title: "Circular Testimonials",
    category: "Testimonios",
    href: "/playground/21st-dev/circular-testimonials",
    provider: "21st.dev",
    kind: "gallery",
    description: "Testimonios animados con fotografías superpuestas y variantes clara y oscura.",
  },
  {
    title: "Sign In",
    category: "Autenticación",
    href: "/playground/21st-dev/sign-in",
    provider: "21st.dev",
    kind: "features",
    description: "Formulario de acceso con imagen lateral, testimonios y animaciones de entrada.",
  },
  {
    title: "Squeeze Carousel",
    category: "Galerías",
    href: "/playground/21st-dev/carousel-squeeze",
    provider: "21st.dev",
    kind: "gallery",
    description: "Carrusel con paneles expansibles, imágenes comprimidas y transiciones animadas.",
  },
  {
    title: "Interactive Map",
    category: "Mapas",
    href: "/playground/21st-dev/interactive-map",
    provider: "21st.dev",
    kind: "features",
    description: "Mapa Leaflet con búsqueda, satélite, marcadores agrupados y figuras de ejemplo.",
  },
  {
    title: "Expand Map",
    category: "Mapas",
    href: "/playground/21st-dev/expand-map",
    provider: "21st.dev",
    kind: "features",
    description: "Tarjeta de ubicación expandible con mapa ilustrativo e inclinación interactiva.",
  },
  {
    title: "Timeline — Aceternity",
    category: "Líneas de tiempo",
    href: "/playground/21st-dev/timeline",
    provider: "21st.dev",
    kind: "features",
    description: "Línea de tiempo vertical con títulos fijos, imágenes y progreso animado al desplazarse.",
  },
  {
    title: "Great UI Revision Timeline",
    category: "Líneas de tiempo",
    href: "/playground/21st-dev/great-ui-revision-timeline",
    provider: "21st.dev",
    kind: "features",
    description: "Historial de revisiones con dial de fechas animado, imágenes y notas de cambios.",
  },
  {
    title: "Interactive Timeline",
    category: "Líneas de tiempo",
    href: "/playground/21st-dev/timeline-02",
    provider: "21st.dev",
    kind: "features",
    description: "Línea de tiempo con selector de años, imágenes y transiciones entre hitos.",
  },
  {
    title: "About Section",
    category: "Secciones de presentación",
    href: "/playground/21st-dev/about-section",
    provider: "21st.dev",
    kind: "features",
    description: "Presentación personal con imagen recortada, estadísticas y textos animados.",
  },
  {
    title: "Interactive Image Accordion",
    category: "Galerías",
    href: "/playground/21st-dev/interactive-image-accordion",
    provider: "21st.dev",
    kind: "gallery",
    description: "Sección con paneles de imagen expansibles y títulos que cambian de orientación.",
  },
  {
    title: "Interactive Selector",
    category: "Galerías",
    href: "/playground/21st-dev/interactive-selector",
    provider: "21st.dev",
    kind: "gallery",
    description: "Galería de experiencias con paneles expandibles, iconos y selección interactiva.",
  },
  {
    title: "Hero Gallery Scroll Animation",
    category: "Heroes",
    href: "/playground/21st-dev/hero-gallery-scroll-animation",
    provider: "21st.dev",
    kind: "features",
    description: "Hero con galería bento que se expande al hacer scroll, en tres variantes.",
  },
  {
    title: "Modern Hero",
    category: "Heroes",
    href: "/playground/21st-dev/modern-hero",
    provider: "21st.dev",
    kind: "features",
    description: "Hero espacial con revelado al hacer scroll, paralaje de imágenes y agenda.",
  },
  {
    title: "File Upload — Imagen y carpeta",
    category: "Carga de archivos",
    href: "/playground/21st-dev/file-upload-1",
    provider: "21st.dev",
    kind: "features",
    description: "Selectores locales de imagen y carpeta con miniaturas, listado y eliminación de archivos.",
  },
  {
    title: "File Upload",
    category: "Carga de archivos",
    href: "/playground/21st-dev/file-upload",
    provider: "21st.dev",
    kind: "features",
    description: "Selector de portada con arrastrar y soltar, validación, vista previa y progreso simulado.",
  },
  {
    title: "QR Code Generator",
    category: "Códigos QR",
    href: "/playground/21st-dev/qr-code-generator",
    provider: "21st.dev",
    kind: "features",
    description: "Visor con descarga PNG y patrón QR decorativo del ejemplo original.",
  },
  {
    title: "Condition Grid",
    category: "Galerías",
    href: "/playground/21st-dev/conditiongrid",
    provider: "21st.dev",
    kind: "gallery",
    description: "Cuadrícula de proyectos con columnas alternadas, títulos superpuestos y entrada animada.",
  },
  {
    title: "Infinite Slider",
    category: "Galerías",
    href: "/playground/21st-dev/infinite-slider",
    provider: "21st.dev",
    kind: "gallery",
    description: "Carrusel continuo de logotipos con animación en bucle y control de pausa.",
  },
  {
    title: "Sticky Scroll Reveal",
    category: "Secciones de características",
    href: "/playground/21st-dev/sticky-scroll-reveal",
    provider: "21st.dev",
    kind: "features",
    description: "Texto destacado al desplazarse y panel visual fijo con contenido sincronizado.",
  },
  {
    title: "Scroll Trigger Animations",
    category: "Animaciones",
    href: "/playground/21st-dev/scroll-trigger-animations",
    provider: "21st.dev",
    kind: "features",
    description: "Contenedores de animación vinculada al scroll con ejemplo de escala y desplazamiento.",
  },
  {
    title: "Scroll Expansion Hero",
    category: "Heroes",
    href: "/playground/21st-dev/scroll-expansion-hero",
    provider: "21st.dev",
    kind: "features",
    description: "Hero con imagen o video que se expande al desplazarse y títulos que se separan.",
  },
  {
    title: "Scroll Gallery",
    category: "Galerías",
    href: "/playground/21st-dev/scroll-gallery",
    provider: "21st.dev",
    kind: "gallery",
    description: "Galería con revelado por franjas y títulos animados al desplazarse.",
  },
  {
    title: "Carousel 10",
    category: "Galerías",
    href: "/playground/21st-dev/c-carousel-10",
    provider: "21st.dev",
    kind: "gallery",
    description: "Carrusel de fotografías con miniaturas superpuestas y selección sincronizada.",
  },
  {
    title: "Ticket Stub Footer",
    category: "Pies de página",
    href: "/playground/21st-dev/ticket-stub-footer",
    provider: "21st.dev",
    kind: "features",
    description: "Footer con talón interactivo, contador animado y marca con efecto de puntos.",
  },
  {
    title: "Immersive Full Screen Navigation",
    category: "Navegación",
    href: "/playground/21st-dev/immersive-full-screen-nav",
    provider: "21st.dev",
    kind: "navigation",
    description: "Menú inmersivo con apertura animada, imágenes y transiciones de texto.",
  },
  {
    title: "Mega Menu Navbar",
    category: "Navegación",
    href: "/playground/21st-dev/navbar2",
    provider: "21st.dev",
    kind: "navigation",
    description: "Barra de navegación con megamenús animados, selector de idioma y menú móvil.",
  },
  {
    title: "Ticket Confirmation Card",
    category: "Boletos",
    href: "/playground/21st-dev/ticket-confirmation-card",
    provider: "21st.dev",
    kind: "event",
    description: "Confirmación de boleto con confeti, datos de compra y código de barras decorativo.",
  },
  {
    title: "Feature Sections",
    category: "Secciones de características",
    href: "/playground/21st-dev/feature-sections",
    provider: "21st.dev",
    kind: "features",
    description: "Dos variantes de características: tarjetas ilustradas e imagen con lista.",
  },
  {
    title: "Cards Slider",
    category: "Galerías",
    href: "/playground/uitripled/cards-slider-shadcnui",
    provider: "UI TripleD",
    kind: "gallery",
    description: "Carrusel arrastrable de tarjetas con imágenes, autores y navegación por flechas.",
  },
  {
    title: "Receipt Tiers",
    category: "Boletos",
    href: "/playground/21st-dev/receipt-tiers",
    provider: "21st.dev",
    kind: "event",
    description: "Planes de precios con diseño de recibo, descuentos y códigos de barras decorativos.",
  },
  {
    title: "Selección de asientos",
    category: "Selectores de asientos",
    href: "/playground/21st-dev/seat-selection",
    provider: "21st.dev",
    kind: "event",
    description: "Selector de asientos por categoría con pasillo, disponibilidad y subtotal.",
  },
  {
    title: "Admit One 3D Holographic Ticket",
    category: "Boletos",
    href: "/playground/21st-dev/admit-one-3-d-holographic-ticket",
    provider: "21st.dev",
    kind: "event",
    description: "Boleto morado con textura animada, reflejos e inclinación 3D.",
  },
  {
    title: "Glass Wallet Card",
    category: "Checkout y pagos",
    href: "/playground/uitripled/glass-wallet-card-shadcnui",
    provider: "UI TripleD",
    kind: "credit-card",
    description: "Billetera con efecto de cristal, saldo, tendencia y acciones de ejemplo.",
  },
  {
    title: "Cinema Ticket",
    category: "Boletos",
    href: "/playground/uitripled/cinema-ticket-shadcnui",
    provider: "UI TripleD",
    kind: "event",
    description: "Boleto de cine con imagen, datos de la función, asiento y QR decorativo.",
  },
  {
    title: "Theater Ticket",
    category: "Boletos",
    href: "/playground/uitripled/theater-ticket-shadcnui",
    provider: "UI TripleD",
    kind: "event",
    description: "Boleto de teatro con textura, perforación, código de barras y talón animado.",
  },
  {
    title: "Conference Ticket",
    category: "Boletos",
    href: "/playground/uitripled/conference-ticket-shadcnui",
    provider: "UI TripleD",
    kind: "event",
    description: "Boleto de conferencia con efecto de cristal, brillo y talón animado.",
  },
  {
    title: "Dashboard Widget 2",
    category: "Selectores de asientos",
    href: "/playground/paceui/dashboard-widget-2",
    provider: "Pace UI",
    kind: "event",
    description: "Mapa de asientos con disponibilidad, selección múltiple y total por categoría.",
  },
  {
    title: "Filmstrip Gallery",
    category: "Galerías",
    href: "/playground/shadcn-ui-blocks/marketing-gallery-filmstrip-gallery",
    provider: "shadcn-ui-blocks",
    kind: "gallery",
    description: "Tira de fotografías con marcos de película y desplazamiento horizontal.",
  },
  {
    title: "Carousel Gallery",
    category: "Galerías",
    href: "/playground/shadcn-ui-blocks/marketing-gallery-carousel-gallery",
    provider: "shadcn-ui-blocks",
    kind: "gallery",
    description: "Carrusel de imágenes con miniaturas, navegación y reproducción automática.",
  },
  {
    title: "Event Registration Countdown",
    category: "Formularios de registro",
    href: "/playground/shadcn-ui-blocks/marketing-hero-forms-event-registration-countdown",
    provider: "shadcn-ui-blocks",
    kind: "event",
    description: "Hero con cuenta regresiva, registro y selección de boletos con total dinámico.",
  },
  {
    title: "Admit One Ticket",
    category: "Boletos",
    href: "/playground/21st-dev/admit-one-ticket",
    provider: "21st.dev",
    kind: "event",
    description: "Boleto con textura animada, perforación e inclinación interactiva.",
  },
  {
    title: "Product Card Event",
    category: "Tarjetas de eventos",
    href: "/playground/shadcn-io/product-card-event",
    provider: "shadcn.io",
    kind: "event",
    description: "Tarjeta de evento con tipos de boleto, cantidad y total.",
  },
  {
    title: "Product Card Virtual Event",
    category: "Tarjetas de eventos",
    href: "/playground/shadcn-io/product-card-virtual-event",
    provider: "shadcn.io",
    kind: "virtual-event",
    description: "Tarjeta de evento virtual con ponentes, plataforma y tipos de entrada.",
  },
  {
    title: "Music Concert Tickets",
    category: "Boletos",
    href: "/playground/shadcn-io/music-concert-tickets",
    provider: "shadcn.io",
    kind: "event",
    description: "Boletos de concierto con categorías, cantidad y desglose del precio animado.",
  },
  {
    title: "Checkout Event Tickets",
    category: "Checkout y pagos",
    href: "/playground/shadcn-io/checkout-event-tickets",
    provider: "shadcn.io",
    kind: "event",
    description: "Checkout con tipos de boleto, cantidad, nombres de asistentes y resumen del pedido.",
  },
  {
    title: "Footer Event",
    category: "Pies de página",
    href: "/playground/shadcn-io/footer-event",
    provider: "shadcn.io",
    kind: "event",
    description: "Footer para eventos con navegación, patrocinadores e información del evento.",
  },
  {
    title: "Music Concert Countdown",
    category: "Cuentas regresivas",
    href: "/playground/shadcn-io/music-concert-countdown",
    provider: "shadcn.io",
    kind: "event",
    description: "Cuenta regresiva animada con fecha, sede y detalles del concierto.",
  },
  {
    title: "Calendar Event Details",
    category: "Calendarios",
    href: "/playground/shadcn-io/calendar-event-details",
    provider: "shadcn.io",
    kind: "event",
    description: "Detalles de reunión con asistentes, enlace y respuesta de asistencia.",
  },
  {
    title: "Credit Card",
    category: "Checkout y pagos",
    href: "/playground/kibo-ui/credit-card",
    provider: "Kibo UI",
    kind: "credit-card",
    description: "Tarjeta visual con frente, reverso y giro interactivo usando datos ficticios.",
  },
  {
    title: "Glass Order Summary",
    category: "Checkout y pagos",
    href: "/playground/uitripled/glass-order-summary-shadcnui",
    provider: "UI TripleD",
    kind: "credit-card",
    description: "Resumen de pedido con efecto de cristal, productos e importes de ejemplo.",
  },
  {
    title: "Glass Checkout Card",
    category: "Checkout y pagos",
    href: "/playground/uitripled/glass-checkout-card-shadcnui",
    provider: "UI TripleD",
    kind: "credit-card",
    description: "Checkout con efecto de cristal, métodos de pago y campos de tarjeta de ejemplo.",
  },
  {
    title: "Card Folder",
    category: "Checkout y pagos",
    href: "/playground/beui/card-folder",
    provider: "BE UI",
    kind: "credit-card",
    description: "Cartera animada con tarjetas y control de visibilidad de datos ficticios.",
  },
] as const;
